@echo Compiling Full Program...
@echo Compiling Globals...
@gcc -c globals.c globals.h TOKENS.h
@echo Compiling Lexer, linking Globals...
@gcc -c lexer.c lexer.h -lglobals
@echo Compiling Parser, linking Lexer and Globals...
@gcc -c parser.c parser.h -llexer -lglobals
@echo Compiling Main, linking Lexer, Parser, and Globals...
@gcc -c main.c -llexer -lparser -lglobals
@echo Building Executable...
@gcc -o runme main.o parser.o lexer.o globals.o
@echo Cleaning Up Object Files...
@del *.o
@echo Cleaning Up Cached Headers...
@del *.gch
